### ISSUE TITLE
ant-design-vue 1.x(for vue2) support

### ISSUE THREAD

**Issue by Alkaidcc** [Simon-He95/vscode-common-intellisense#32]
The old project of vue2 is also worth enjoying the charm of intelligent completion 🥳

**Comment by Simon-He95** [comment]
This will be a big job. I currently have no plans to maintain ant-design-vue1. If you are interested, you can refer to the ant-design-vue5 file and make a copy to make corresponding changes. Welcome to PR.

**Comment by Alkaidcc** [comment]
fixed in #39
