### ISSUE TITLE
The description is in English, not Chinese

### ISSUE THREAD

**Issue by fslflame** [Simon-He95/vscode-common-intellisense#33]
![image](https://github.com/Simon-He95/vscode-common-intellisense/assets/101857530/46af55be-01f2-4a58-b91d-e00c67bb0f5e)

**Comment by Simon-He95** [comment]
v0.0.81 will be fixed
<img width="1066" alt="image" src="https://github.com/Simon-He95/vscode-common-intellisense/assets/57086651/b815161e-d108-4487-a275-124036b87f5d">
