### ISSUE TITLE
feat: support vant2

### ISSUE THREAD

**Issue by lzxjs** [Simon-He95/vscode-common-intellisense#37]
求新增vant2的支持，很需要：https://vant-contrib.gitee.io/vant/v2/#/zh-CN/field

**Comment by Simon-He95** [comment]
I am very happy to receive your issue, but the author has limited energy and cannot support every version of so many component libraries. Currently, only the latest version is supported. If necessary, you can consider raising a PR and refer to the latest version of the file to make a copy. Changes, hope you understand

**Comment by c2kaka** [comment]
> I am very happy to receive your issue, but the author has limited energy and cannot support every version of so many component libraries. Currently, only the latest version is supported. If necessary, you can consider raising a PR and refer to the latest version of the file to make a copy. Changes, hope you understand

I'd love to know how to maintain the vscode snippets of the corresponding components if there is an update to the component library. Is it obtained by using a script to parse the source code of the corresponding library?

**Comment by Simon-He95** [comment]
> > I am very happy to receive your issue, but the author has limited energy and cannot support every version of so many component libraries. Currently, only the latest version is supported. If necessary, you can consider raising a PR and refer to the latest version of the file to make a copy. Changes, hope you understand
> 
> I'd love to know how to maintain the vscode snippets of the corresponding components if there is an update to the component library. Is it obtained by using a script to parse the source code of the corresponding library?

Each large version of the component library has a corresponding json file configuration. If it is updated, the corresponding json needs to be updated. We can try to obtain the corresponding component library document through a script, and then convert it into the corresponding json.
