### ISSUE TITLE
使用插件和gif效果图不太一样，很多地方都没有正常使用

### ISSUE THREAD

**Issue by FairyWorld** [Simon-He95/vscode-common-intellisense#45]
为什么我用了插件和你的效果不太一样，图一是你的gif截图，后面的是我的效果。
1. 图2代码提示没有效果图右侧的远程文档链接, 提示的语法内容好像也不对
2. 图3提示的type属性确认后会把多余的字符"类型  默认：—"加到属性里, 变成图4的输出
3. 图5是把鼠标悬浮到el-button上才出现效果图的文档说明, 其他情况好像都无法触发

#### 图1
![image](https://github.com/Simon-He95/vscode-common-intellisense/assets/32956212/ca6b8dd0-fbd6-458d-aa3e-382fc1d97230)

#### 图2
![image](https://github.com/Simon-He95/vscode-common-intellisense/assets/32956212/0ac962c9-71fc-48dd-bdf8-3f25cac7fa6f)

#### 图3
![image](https://github.com/Simon-He95/vscode-common-intellisense/assets/32956212/0e2807b8-8b5c-46d7-9eaa-567d40ac472c)

#### 图4
![image](https://github.com/Simon-He95/vscode-common-intellisense/assets/32956212/a674bc79-aeb5-486a-bd39-04dc3d03f705)

#### 图5
![image](https://github.com/Simon-He95/vscode-common-intellisense/assets/32956212/89563c0c-39ef-432c-9f2b-98c3ea5b9616)

**Comment by Simon-He95** [comment]
文档是在属性中敲空格
![屏幕录制2024-01-10 12 56 17](https://github.com/Simon-He95/vscode-common-intellisense/assets/57086651/fd8c2c45-82f1-4b80-9934-665e9c9d6c0b)

**Comment by Simon-He95** [comment]
Due to lack of evidence I will close it for now

**Comment by DaYuMoon** [comment]
> > 文档是在属性中敲空格 ![屏幕录制2024-01-10 12 56 17](https://private-user-images.githubusercontent.com/57086651/295453115-fd8c2c45-82f1-4b80-9934-665e9c9d6c0b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjM4OTgsIm5iZiI6MTcwNDg2MzU5OCwicGF0aCI6Ii81NzA4NjY1MS8yOTU0NTMxMTUtZmQ4YzJjNDUtODJmMS00YjgwLTk5MzQtNjY1ZTljOWQ2YzBiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA1MTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YTExYWUwMzIzNGFlMThmZmUyMjNjYzQyYTY4MGQyMmMxZDI4Yjk3OTI4OTNmYjEzZWMwNGI3YzY5MjUyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tZ3vN6SkRoYdZ-SOzuf3g2Z-3Wiw0BozWYZf5NV3bG0)
> >       
> >         [
> >           
> >             ![屏幕录制2024-01-10 12 56 17](https://private-user-images.githubusercontent.com/57086651/295453115-fd8c2c45-82f1-4b80-9934-665e9c9d6c0b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjM4OTgsIm5iZiI6MTcwNDg2MzU5OCwicGF0aCI6Ii81NzA4NjY1MS8yOTU0NTMxMTUtZmQ4YzJjNDUtODJmMS00YjgwLTk5MzQtNjY1ZTljOWQ2YzBiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA1MTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YTExYWUwMzIzNGFlMThmZmUyMjNjYzQyYTY4MGQyMmMxZDI4Yjk3OTI4OTNmYjEzZWMwNGI3YzY5MjUyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tZ3vN6SkRoYdZ-SOzuf3g2Z-3Wiw0BozWYZf5NV3bG0)
> >           
> >         ](https://private-user-images.githubusercontent.com/57086651/295453115-fd8c2c45-82f1-4b80-9934-665e9c9d6c0b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjM4OTgsIm5iZiI6MTcwNDg2MzU5OCwicGF0aCI6Ii81NzA4NjY1MS8yOTU0NTMxMTUtZmQ4YzJjNDUtODJmMS00YjgwLTk5MzQtNjY1ZTljOWQ2YzBiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA1MTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YTExYWUwMzIzNGFlMThmZmUyMjNjYzQyYTY4MGQyMmMxZDI4Yjk3OTI4OTNmYjEzZWMwNGI3YzY5MjUyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tZ3vN6SkRoYdZ-SOzuf3g2Z-3Wiw0BozWYZf5NV3bG0)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/57086651/295453115-fd8c2c45-82f1-4b80-9934-665e9c9d6c0b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjM4OTgsIm5iZiI6MTcwNDg2MzU5OCwicGF0aCI6Ii81NzA4NjY1MS8yOTU0NTMxMTUtZmQ4YzJjNDUtODJmMS00YjgwLTk5MzQtNjY1ZTljOWQ2YzBiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA1MTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YTExYWUwMzIzNGFlMThmZmUyMjNjYzQyYTY4MGQyMmMxZDI4Yjk3OTI4OTNmYjEzZWMwNGI3YzY5MjUyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tZ3vN6SkRoYdZ-SOzuf3g2Z-3Wiw0BozWYZf5NV3bG0)
> >         
> >        [ ![屏幕录制2024-01-10 12 56 17](https://private-user-images.githubusercontent.com/57086651/295453115-fd8c2c45-82f1-4b80-9934-665e9c9d6c0b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjM4OTgsIm5iZiI6MTcwNDg2MzU5OCwicGF0aCI6Ii81NzA4NjY1MS8yOTU0NTMxMTUtZmQ4YzJjNDUtODJmMS00YjgwLTk5MzQtNjY1ZTljOWQ2YzBiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA1MTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YTExYWUwMzIzNGFlMThmZmUyMjNjYzQyYTY4MGQyMmMxZDI4Yjk3OTI4OTNmYjEzZWMwNGI3YzY5MjUyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tZ3vN6SkRoYdZ-SOzuf3g2Z-3Wiw0BozWYZf5NV3bG0) ](https://private-user-images.githubusercontent.com/57086651/295453115-fd8c2c45-82f1-4b80-9934-665e9c9d6c0b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjM4OTgsIm5iZiI6MTcwNDg2MzU5OCwicGF0aCI6Ii81NzA4NjY1MS8yOTU0NTMxMTUtZmQ4YzJjNDUtODJmMS00YjgwLTk5MzQtNjY1ZTljOWQ2YzBiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA1MTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YTExYWUwMzIzNGFlMThmZmUyMjNjYzQyYTY4MGQyMmMxZDI4Yjk3OTI4OTNmYjEzZWMwNGI3YzY5MjUyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tZ3vN6SkRoYdZ-SOzuf3g2Z-3Wiw0BozWYZf5NV3bG0)
> >       
> >         [
> >           
> >             ![屏幕录制2024-01-10 12 56 17](https://private-user-images.githubusercontent.com/57086651/295453115-fd8c2c45-82f1-4b80-9934-665e9c9d6c0b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjM4OTgsIm5iZiI6MTcwNDg2MzU5OCwicGF0aCI6Ii81NzA4NjY1MS8yOTU0NTMxMTUtZmQ4YzJjNDUtODJmMS00YjgwLTk5MzQtNjY1ZTljOWQ2YzBiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA1MTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YTExYWUwMzIzNGFlMThmZmUyMjNjYzQyYTY4MGQyMmMxZDI4Yjk3OTI4OTNmYjEzZWMwNGI3YzY5MjUyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tZ3vN6SkRoYdZ-SOzuf3g2Z-3Wiw0BozWYZf5NV3bG0)
> >           
> >         ](https://private-user-images.githubusercontent.com/57086651/295453115-fd8c2c45-82f1-4b80-9934-665e9c9d6c0b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjM4OTgsIm5iZiI6MTcwNDg2MzU5OCwicGF0aCI6Ii81NzA4NjY1MS8yOTU0NTMxMTUtZmQ4YzJjNDUtODJmMS00YjgwLTk5MzQtNjY1ZTljOWQ2YzBiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA1MTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YTExYWUwMzIzNGFlMThmZmUyMjNjYzQyYTY4MGQyMmMxZDI4Yjk3OTI4OTNmYjEzZWMwNGI3YzY5MjUyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tZ3vN6SkRoYdZ-SOzuf3g2Z-3Wiw0BozWYZf5NV3bG0)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/57086651/295453115-fd8c2c45-82f1-4b80-9934-665e9c9d6c0b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjM4OTgsIm5iZiI6MTcwNDg2MzU5OCwicGF0aCI6Ii81NzA4NjY1MS8yOTU0NTMxMTUtZmQ4YzJjNDUtODJmMS00YjgwLTk5MzQtNjY1ZTljOWQ2YzBiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA1MTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YTExYWUwMzIzNGFlMThmZmUyMjNjYzQyYTY4MGQyMmMxZDI4Yjk3OTI4OTNmYjEzZWMwNGI3YzY5MjUyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tZ3vN6SkRoYdZ-SOzuf3g2Z-3Wiw0BozWYZf5NV3bG0)
> >         
> >        [ ](https://private-user-images.githubusercontent.com/57086651/295453115-fd8c2c45-82f1-4b80-9934-665e9c9d6c0b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjM4OTgsIm5iZiI6MTcwNDg2MzU5OCwicGF0aCI6Ii81NzA4NjY1MS8yOTU0NTMxMTUtZmQ4YzJjNDUtODJmMS00YjgwLTk5MzQtNjY1ZTljOWQ2YzBiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA1MTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YTExYWUwMzIzNGFlMThmZmUyMjNjYzQyYTY4MGQyMmMxZDI4Yjk3OTI4OTNmYjEzZWMwNGI3YzY5MjUyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tZ3vN6SkRoYdZ-SOzuf3g2Z-3Wiw0BozWYZf5NV3bG0)
> 
> 还是一样，我看下是不是和什么东西冲突了

请问，解决了吗，我貌似遇到了同样的问题。

**Comment by DaYuMoon** [comment]
> 还是一样，我看下是不是和什么东西冲突了

请问，解决了吗，我貌似遇到了同样的问题。

**Comment by Simon-He95** [comment]
> > 还是一样，我看下是不是和什么东西冲突了
> 
> 请问，解决了吗，我貌似遇到了同样的问题。

我并没有复现上述的问题，如果你有遇到问题，可以提供更加详细的复现步骤，或者仓库地址，谢谢
