### ISSUE TITLE
在vscode的扩展商店中，文档无法切换到中文

### ISSUE THREAD

**Issue by mvpyangxu** [Simon-He95/vscode-common-intellisense#46]
![CleanShot 2024-01-10 at 14 22 24](https://github.com/Simon-He95/vscode-common-intellisense/assets/54459610/4575c51a-7a8b-4a35-872d-182a17c34fae)

**Comment by Simon-He95** [comment]
It's ok now

**Comment by mvpyangxu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
