### ISSUE TITLE
Slots 操作区会导致页面抖动

### ISSUE THREAD

**Issue by hooray** [Simon-He95/vscode-common-intellisense#51]
https://github.com/Simon-He95/vscode-common-intellisense/assets/1574903/7fa7b214-714a-4351-a849-67765b335460

只要页面中有 Slots ，每次换行都会抖动，可以看到 Slots 操作区每次换行都会先隐藏再显示，如果页面上有多个 Slots ，抖动更明显

目前只能通过关闭 Slots 操作区解决

**Comment by Simon-He95** [comment]
这是vscode默认行为，没办法处理
