### ISSUE TITLE
咨询个问题

### ISSUE THREAD

**Issue by xu-Aurora** [Simon-He95/vscode-common-intellisense#59]
1. 该插件是否需要联网才能使用？我弄到内网安装可以使用？
2. 是不是不支持在vue项目的jsx文件中使用？因为没有提示。
3. 我在template使用时，只提示大写的，而不是你提供的demo里面的小写组件。比如我输入van， 提示VanToast，而不是van-toast

**Comment by xu-Aurora** [comment]
想达到你这个的demo一样的效果，需要其他什么配置嘛？https://github.com/Simon-He95/vscode-common-intellisense/blob/main/assets/vant.gif

**Comment by Simon-He95** [comment]
> 1. 该插件是否需要联网才能使用？我弄到内网安装可以使用？
> 2. 是不是不支持在vue项目的jsx文件中使用？因为没有提示。
> 3. 我在template使用时，只提示大写的，而不是你提供的demo里面的小写组件。比如我输入van， 提示VanToast，而不是van-toast

请提供一个使用的demo场景，因为我不用jsx可能存在场景没有兼容到，提供demo，会再后续兼容的

**Comment by Simon-He95** [comment]
由于缺少复现的repo，此issue暂时关闭，待提供复现repo，欢迎随时再打开
