### ISSUE TITLE
关于自定义封装组件使用

### ISSUE THREAD

**Issue by cdmcgitedu** [Simon-He95/vscode-common-intellisense#61]
自己封装了elementUi2,如何在vscode中使用，这样配置也无法使用@hr/element-ui
![QQ图片20240416085800](https://github.com/Simon-He95/vscode-common-intellisense/assets/135135819/ad847912-9b1f-4d02-b60f-7b4e2d466d51)
![QQ图片20240416085815](https://github.com/Simon-He95/vscode-common-intellisense/assets/135135819/e2e59d9f-2957-4017-8858-b08743e012b5)

**Comment by cdmcgitedu** [comment]
> 如果你希望有提示的话你需要在package.json安装element-ui

没有办法进行兼容吗，比如强行开始element-ui提示

**Comment by Simon-He95** [comment]
试一下这个，刚更新了一下
https://github.com/Simon-He95/vscode-common-intellisense?tab=readme-ov-file#configuration

**Comment by cdmcgitedu** [comment]
> 试一下这个，刚更新了一下 https://github.com/Simon-He95/vscode-common-intellisense?tab=readme-ov-file#configuration

![QQ图片20240416145814](https://github.com/Simon-He95/vscode-common-intellisense/assets/135135819/a492e0a9-0c96-42ad-8555-68690cde2729)
还是不行，输入el-还是之前的

**Comment by Simon-He95** [comment]
...不是这样配置的这个是里面带类型和描述的，在vscode settings中你应该是
```
"common-intellisense.alias":{
   "@xxx/element-ui": "elementUi2"
}
```

**Comment by cdmcgitedu** [comment]
> ...不是这样配置的这个是里面带类型和描述的，在vscode settings中你应该是
> 
> ```
> "common-intellisense.alias":{
>    "@xxx/element-ui": "elementUi2"
> }
> ```
谢谢大佬~完美
