### ISSUE TITLE
从1.42版本开始，类型提示会非常卡

### ISSUE THREAD

**Issue by hws786** [Simon-He95/vscode-common-intellisense#62]
<img width="374" alt="image" src="https://github.com/Simon-He95/vscode-common-intellisense/assets/94960075/0507d81d-b807-44e1-bf48-5c53e7af5a13">

鼠标放在变量上，一直提示正在加载，几分钟都不出提示，退回1.41版本后秒出提示

**Comment by Simon-He95** [comment]
Please try it on the latest version. If the problem still exists, you can provide a reproducible demo and steps to reproduce it.

**Comment by Simon-He95** [comment]
try to use v0.1.48，Test to see if it is fixed

**Comment by Simon-He95** [comment]
> v0.1.48 has been tested and is working fine.

thanks for your help
