### ISSUE TITLE
会自动往工作区.vscode配置添加配置项 能否关闭

### ISSUE THREAD

**Issue by cjh-store** [Simon-He95/vscode-common-intellisense#63]
![image](https://github.com/Simon-He95/vscode-common-intellisense/assets/88535245/fbbeab32-8059-4186-973b-3a820d679131)
删除后一保存 又自动加上了

**Comment by Simon-He95** [comment]
v0.1.50 将不在自动添加了，除非你存在使用多个组件库，为了解决组件库的前缀命名冲突的情况下，选择了某一个ui时，才会添加
