### ISSUE TITLE
Hope to support TinyVue🖖

### ISSUE THREAD

**Issue by kagol** [Simon-He95/vscode-common-intellisense#64]
TinyVue is an enterprise-class UI component library of OpenTiny community, support both Vue.js 2 and Vue.js 3, as well as PC and mobile.

Website: https://opentiny.design/tiny-vue
GitHub: https://github.com/opentiny/tiny-vue

API list of all components:
https://github.com/opentiny/tiny-vue/tree/dev/examples/sites/demos/apis

**Comment by Simon-He95** [comment]
If the [upvote](https://github.com/microsoft/vscode/wiki/Issues-Triaging#up-voting-a-feature-request) exceeds 20, it will be added to the supported plan

**Comment by Simon-He95** [comment]
374ec4dea3cf536cad6377d51399f37e825310e4
