### ISSUE TITLE
如果我想要使用的ui组件库，在这个插件中没有(比如公司内部的)，我可以怎么做呢

### ISSUE THREAD

**Issue by tyj-321** [Simon-He95/vscode-common-intellisense#67]
首先，我非常喜欢这个插件，它能大幅度提升开发体验

但是我的目标组件库是一个公司内的组件库，这个插件并不支持，我有什么办法在我的目标组件库中使用吗

我看到实际每个组件库都是一个一个的api的json文件，我可以把插件源码copy下来自己加配置文件吗，但是这样我认为就没必要再发布一个插件了，毕竟这个插件也只是在公司内部使用

**Comment by Simon-He95** [comment]
> 首先，我非常喜欢这个插件，它能大幅度提升开发体验
> 
> 但是我的目标组件库是一个公司内的组件库，这个插件并不支持，我有什么办法在我的目标组件库中使用吗
> 
> 我看到实际每个组件库都是一个一个的api的json文件，我可以把插件源码copy下来自己加配置文件吗，但是这样我认为就没必要再发布一个插件了，毕竟这个插件也只是在公司内部使用

你可以fork下来，按照其它的规则，去添加你们内部的组件相关内容，然后执行脚本 `pnpm build & pnpm pack` 打包成.vsix文件再自行安装即可

<img width="296" alt="image" src="https://github.com/user-attachments/assets/8bfca38f-ee77-4560-b346-1b8391394660">
